import http from 'node:http';
const PORT=process.env.PORT||3000, API='https://api.systeme.io/api', KEY=process.env.SYSTEME_API_KEY;
function j(res,s,d){res.writeHead(s,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(d));}
async function sio(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'X-API-Key':KEY,'accept':'application/json','content-type':'application/json'}});const t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}return {status:r.status,ok:r.ok,data:d,remaining:r.headers.get('x-ratelimit-remaining')};}
const sourceWp='https://brulafineavis.wordpress.com/';
const pages=[
{name:'Brulafine Avis 2026',title:'Brulafine Avis 2026 : analyse indépendante des avis clients',intro:'Analyse indépendante des retours Brulafine : écarts entre plateformes, composition annoncée, précautions et points à vérifier avant achat.',facts:['Trustpilot : 3,1/5 sur 122 avis au 1er octobre 2026','Avis Vérifiés : 4,6/5 sur 5 251 avis historiques','Composition annoncée : thé vert, guarana, noix de kola','Témoignages ≠ preuve clinique','Vérifier toute offre de coaching associée'],paras:['Les avis Brulafine sont très contrastés selon la plateforme consultée. Nous affichons volontairement les signaux positifs et négatifs au lieu de choisir une seule moyenne.','Des consommateurs rapportent une expérience positive, tandis que d’autres évoquent une absence d’effet ressenti ou contestent des prélèvements liés à un service de coaching. Ces témoignages restent des expériences individuelles.','Le fabricant met en avant du thé vert, du guarana et de la noix de kola. Ces ingrédients peuvent apporter de la caféine ; la formule et les dosages doivent être vérifiés sur l’étiquette du produit acheté.','Notre méthode sépare les informations officielles, les témoignages de consommateurs et les conclusions médicales. Une perte de poids racontée dans un avis n’est pas une preuve clinique.'],next:'Voir les avis clients'},
{name:'Brulafine Avis Clients',title:'Brulafine avis clients : positifs, négatifs et tendances 2026',intro:'Lecture croisée des avis clients Brulafine, avec distinction entre satisfaction de service, effet perçu et faits vérifiables.',facts:['Avis positifs sur livraison et satisfaction','Avis négatifs sur absence d’effet perçu','Signalements autour du coaching','Méthodes de collecte différentes selon les plateformes','Aucune conclusion tirée d’un témoignage isolé'],paras:['Les avis positifs mentionnent notamment la livraison, le service client et des résultats perçus.','Les avis négatifs récents visibles sur Trustpilot mentionnent notamment une absence d’effet perçu et des contestations autour d’un service de coaching.','L’écart entre Trustpilot et Avis Vérifiés montre qu’une note moyenne doit toujours être replacée dans son contexte de collecte et de période.','Nous décrivons les thèmes récurrents sans transformer une accusation individuelle en fait général.'],next:'Voir la composition'},
{name:'Brulafine Composition',title:'Brulafine composition : thé vert, guarana et noix de kola',intro:'Analyse de la composition annoncée par Brulafine et des précautions liées notamment aux sources de caféine.',facts:['Thé vert','Guarana','Noix de kola','Caféine potentielle','Vérifier les dosages sur l’étiquette'],paras:['Le contenu officiel Brulafine met en avant trois actifs principaux : thé vert, guarana et noix de kola.','La présence d’un ingrédient végétal ne suffit pas à démontrer l’efficacité du produit fini sur la perte de poids.','Le guarana et la noix de kola sont naturellement associés à la caféine ; le thé vert peut également en contenir.','Les personnes sensibles aux stimulants ou suivant un traitement devraient demander conseil à un professionnel de santé.'],next:'Avant d’acheter'},
{name:'Brulafine Prix et Achat',title:'Brulafine prix et achat : les contrôles avant de payer',intro:'Panier final, services associés, coaching, renouvellement et conditions commerciales : les points à vérifier avant commande.',facts:['Vérifier le prix total TTC','Identifier tout coaching ou service associé','Lire les conditions de renouvellement','Conserver le récapitulatif de commande','Contrôler les modalités de remboursement'],paras:['Le coût réel ne se limite pas au prix affiché du flacon : il faut vérifier les services associés et les conditions commerciales.','Plusieurs avis récents signalent des contestations autour de prélèvements liés au coaching. Cela justifie une lecture attentive du panier et des conditions applicables.','Conservez la confirmation de commande, le détail du panier et les conditions affichées au moment de l’achat.','Notre objectif est de documenter les points à contrôler, pas de présenter un témoignage comme une conclusion juridique.'],next:'Notre méthode'},
{name:'Méthodologie Brulafine Avis',title:'Méthodologie Brulafine Avis : sources, limites et indépendance',intro:'Sources primaires, plateformes d’avis, contradictions conservées et séparation stricte entre témoignage et preuve.',facts:['Sources officielles pour la composition','Plateformes d’avis pour les expériences clients','Contradictions affichées','Aucun faux témoignage','Mises à jour datées'],paras:['Nous utilisons les informations officielles pour la composition déclarée et les plateformes d’avis pour documenter l’expérience client.','Une plateforme d’avis n’est jamais assimilée à une étude clinique.','Quand deux sources donnent des signaux opposés, nous conservons les deux et expliquons leurs limites.','Ce site est éditorial et indépendant ; toute future relation commerciale devra être signalée explicitement.'],next:'Retour à l’avis complet'}
];
function val(p,i,page){const d=(p.description||'').toLowerCase(),t=p.type||'';
if(t==='image')return 'green tea, guarana berries, kola nut, editorial consumer review, neutral magazine photography';
if(t==='buttonText')return page.next;
if(t==='headline')return d.includes('hero')?page.title:page.facts[i%page.facts.length];
if(t==='bulletList')return page.facts.join('\n');
if(t==='text'){if(d.includes('built with'))return 'Construit avec © <a href="https://systeme.io" style="color:#000">systeme.io</a>';if(d.includes('hero'))return page.intro;if(d.includes('testimonial')||d.includes('social proof'))return 'Nous n’utilisons aucun témoignage inventé : les expériences citées restent attribuées aux plateformes d’avis.';if(d.includes('footer'))return 'Guide indépendant Brulafine Avis · Sources datées · Vérification éditoriale : 1 octobre 2026.';let base='<p>'+page.paras[i%page.paras.length]+'</p>';if(page.name==='Brulafine Avis 2026'&&i===0)base+='<p>Lire également notre dossier principal : <a href="'+sourceWp+'">Brulafine Avis 2026</a>.</p>';return base;}return page.paras[i%page.paras.length];}
async function audit(url){try{const r=await fetch(url,{redirect:'follow'}),html=await r.text();const tx=(re)=>html.match(re)?.[1]?.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()||null;return {status:r.status,finalUrl:r.url,title:tx(/<title[^>]*>([\s\S]*?)<\/title>/i),h1:tx(/<h1[^>]*>([\s\S]*?)<\/h1>/i),canonical:html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']*)/i)?.[1]||null,length:html.length,hasWp:html.includes(sourceWp)}}catch(e){return {error:String(e)}}}
async function run(){try{let fs=await sio('/funnels?limit=100');let funnel=fs.data.items.find(x=>x.name==='Brulafine Avis — SEO 2026');if(!funnel){let cr=await sio('/funnels',{method:'POST',body:JSON.stringify({name:'Brulafine Avis — SEO 2026'})});console.log('CREATE_FUNNEL '+JSON.stringify(cr));if(!cr.ok)throw new Error(JSON.stringify(cr));funnel=cr.data;}
const tpl=await sio('/page-editor/page-template',{method:'POST',body:JSON.stringify({type:'sales_page'})});if(!tpl.ok)throw new Error(JSON.stringify(tpl));
let ss=await sio('/funnels/'+funnel.id+'/steps?limit=100');let steps=ss.data.items;
for(const page of pages){let step=steps.find(x=>x.name===page.name);if(!step){const cr=await sio('/funnels/'+funnel.id+'/steps',{method:'POST',body:JSON.stringify({name:page.name,type:'sales_page'})});console.log('CREATE_PAGE '+JSON.stringify(cr));if(!cr.ok)continue;step=cr.data;steps.push(step);}
const placeholders={};tpl.data.placeholders.forEach((p,i)=>placeholders[p.name]=val(p,i,page));
const put=await sio('/pages/'+step.pageId+'/content/from-template',{method:'PUT',body:JSON.stringify({templateId:tpl.data.templateId,placeholders})});
console.log('POPULATE '+JSON.stringify({name:page.name,stepId:step.id,pageId:step.pageId,url:step.url,status:put.status,ok:put.ok,remaining:put.remaining,error:put.ok?null:put.data}));}
await new Promise(r=>setTimeout(r,2500));
const verify=await sio('/funnels/'+funnel.id+'/steps?limit=100');console.log('FINAL_STEPS '+JSON.stringify(verify));
for(const s of verify.data.items){console.log('PUBLIC_AUDIT '+JSON.stringify({name:s.name,url:s.url,audit:await audit(s.url)}));}
}catch(e){console.error('BUILD_ERROR '+String(e?.stack||e));}}
const app=http.createServer((req,res)=>req.url==='/health'?j(res,200,{ok:true,service:'brulafine-systeme-builder'}):j(res,200,{ok:true}));
app.listen(PORT,'0.0.0.0',()=>{console.log('ready',PORT);run();});